name: sharelatex

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  sharelatex-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Clone and reset to specific commit
        run: |
          git clone https://github.com/overleaf/overleaf.git
          
      - name: Prepare Environment
        run: |
          echo "REVERSION=$(git -C overleaf rev-parse HEAD)" >> $GITHUB_ENV
          echo ${{ env.REVERSION }}
